/**
 * ClaudeOS v3 Kernel - Build Pipeline
 *
 * At build time:
 *   1. Scans for installed modules
 *   2. Resolves dependency graph
 *   3. Generates src/generated/module-registry.ts with dynamic imports
 *   4. Generates src/generated/api-routes.ts with route handlers
 *   5. Generates supervisord.conf from service definitions
 *   6. Generates Dockerfile from template
 *   7. Validates everything compiles
 */

import * as fs from 'fs';
import * as path from 'path';
import {
  discoverModules,
  loadModulesConfig,
  buildStaticRegistry,
  validateManifest,
} from './module-loader';
import type {
  ModuleManifest,
  ServiceDefinition,
  BuildManifest,
} from './types';

const ROOT_DIR = path.resolve(__dirname, '..');
const GENERATED_DIR = path.join(ROOT_DIR, 'src', 'generated');
const TEMPLATES_DIR = ROOT_DIR;

// ---------------------------------------------------------------------------
// Ensure directories
// ---------------------------------------------------------------------------

function ensureDir(dir: string): void {
  fs.mkdirSync(dir, { recursive: true });
}

// ---------------------------------------------------------------------------
// Generate module-registry.ts
// ---------------------------------------------------------------------------

function generateModuleRegistry(
  modules: Array<{ manifest: ModuleManifest; modulePath: string }>,
): string {
  const imports: string[] = [];
  const panelEntries: string[] = [];
  const activityBarEntries: string[] = [];
  const sidebarEntries: string[] = [];
  const settingsEntries: string[] = [];
  const statusBarEntries: string[] = [];
  const bottomPanelEntries: string[] = [];
  const moduleEntries: string[] = [];

  for (const { manifest, modulePath } of modules) {
    // Read the module entry to extract definitions statically
    const entryPath = path.join(modulePath, manifest.main);
    if (!fs.existsSync(entryPath)) continue;

    // We read the manifest to get the module's declared extensions
    // At build time, we create import paths relative to the module location
    const relPath = path.relative(ROOT_DIR, modulePath).replace(/\\/g, '/');
    const isNodeModule = relPath.startsWith('node_modules/');
    const importBase = isNodeModule
      ? manifest.name
      : './' + relPath;

    moduleEntries.push(`  '${manifest.name}': {
    name: '${manifest.name}',
    version: '${manifest.version}',
    description: ${JSON.stringify(manifest.description)},
    path: '${relPath}',
    enabled: true,
  }`);
  }

  const code = `// AUTO-GENERATED BY kernel/build.ts - DO NOT EDIT
// Generated at: ${new Date().toISOString()}

import type { ModuleRegistry } from '@kernel/types';

// Module component lazy loaders
// Modules register their components via the registry at runtime
export const panelComponents: Record<string, () => Promise<{ default: React.ComponentType }>> = {
${panelEntries.join(',\n')}
};

export const sidebarComponents: Record<string, () => Promise<{ default: React.ComponentType }>> = {
${sidebarEntries.join(',\n')}
};

export const settingsComponents: Record<string, () => Promise<{ default: React.ComponentType }>> = {
${settingsEntries.join(',\n')}
};

export const statusBarComponents: Record<string, () => Promise<{ default: React.ComponentType }>> = {
${statusBarEntries.join(',\n')}
};

export const bottomPanelComponents: Record<string, () => Promise<{ default: React.ComponentType }>> = {
${bottomPanelEntries.join(',\n')}
};

// Static module metadata (no dynamic imports needed)
export const moduleMetadata: Record<string, {
  name: string;
  version: string;
  description: string;
  path: string;
  enabled: boolean;
}> = {
${moduleEntries.join(',\n')}
};

// Empty registry - populated at runtime by module-loader
export const registry: ModuleRegistry = {
  modules: {},
  panels: [],
  activityBarItems: [],
  sidebarSections: [],
  settingsPages: [],
  statusBarItems: [],
  bottomPanelTabs: [],
  apiRoutes: [],
  wsHandlers: [],
  services: [],
};
`;

  return code;
}

// ---------------------------------------------------------------------------
// Generate api-routes.ts
// ---------------------------------------------------------------------------

function generateApiRoutes(
  modules: Array<{ manifest: ModuleManifest; modulePath: string }>,
): string {
  const code = `// AUTO-GENERATED BY kernel/build.ts - DO NOT EDIT
// Generated at: ${new Date().toISOString()}

import type { ApiRouteDefinition } from '@kernel/types';

// Module API routes are loaded dynamically at server startup
// This file provides static metadata for the routes

export const moduleApiRoutes: ApiRouteDefinition[] = [];
`;

  return code;
}

// ---------------------------------------------------------------------------
// Generate supervisord.conf
// ---------------------------------------------------------------------------

function generateSupervisordConf(services: ServiceDefinition[]): string {
  const templatePath = path.join(TEMPLATES_DIR, 'supervisord.conf.template');

  let template: string;
  if (fs.existsSync(templatePath)) {
    template = fs.readFileSync(templatePath, 'utf-8');
  } else {
    template = `[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid
loglevel=info

[program:claudeos]
command=node --import tsx kernel/server.ts
directory=/app
environment=NODE_ENV="production"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=10
startretries=3
startsecs=5

# MODULE_SERVICES_PLACEHOLDER
`;
  }

  // Generate service blocks for module services
  const serviceBlocks: string[] = [];
  for (const svc of services) {
    const args = svc.args ? ' ' + svc.args.join(' ') : '';
    const envParts: string[] = [];
    if (svc.env) {
      for (const [key, val] of Object.entries(svc.env)) {
        envParts.push(`${key}="${val}"`);
      }
    }
    const envLine = envParts.length > 0 ? `\nenvironment=${envParts.join(',')}` : '';
    const userLine = svc.user ? `\nuser=${svc.user}` : '';
    const priority = svc.priority || 20;
    const startSecs = svc.startDelay || 3;

    serviceBlocks.push(`[program:${svc.name}]
command=${svc.command}${args}
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=${priority}
startretries=3
startsecs=${startSecs}${envLine}${userLine}
`);
  }

  return template.replace(
    '# MODULE_SERVICES_PLACEHOLDER',
    serviceBlocks.join('\n'),
  );
}

// ---------------------------------------------------------------------------
// Generate Dockerfile
// ---------------------------------------------------------------------------

function generateDockerfile(services: ServiceDefinition[]): string {
  const templatePath = path.join(TEMPLATES_DIR, 'Dockerfile.template');

  let template: string;
  if (fs.existsSync(templatePath)) {
    template = fs.readFileSync(templatePath, 'utf-8');
  } else {
    template = `# ClaudeOS v3 - Auto-generated Dockerfile
FROM node:22-slim AS base

RUN apt-get update && apt-get install -y \\
  supervisor curl git python3 python3-pip \\
  openssh-client openssl ripgrep fd-find jq \\
  && rm -rf /var/lib/apt/lists/*

# Install Claude Code CLI
RUN npm install -g @anthropic-ai/claude-code

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json* ./
RUN npm ci --production=false

# Copy source
COPY . .

# Build
RUN npm run build

# MODULE_INSTALL_PLACEHOLDER

# Copy generated configs
COPY supervisord.conf /etc/supervisord.conf
COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

# Create data directory
RUN mkdir -p /data/sessions /data/workspace

EXPOSE 3000

ENTRYPOINT ["/app/entrypoint.sh"]
`;
  }

  // Generate module install commands
  const installCommands: string[] = [];
  for (const svc of services) {
    // Modules can specify install commands via their service definitions
    // This is a hook for modules that need system-level packages
  }

  return template.replace(
    '# MODULE_INSTALL_PLACEHOLDER',
    installCommands.join('\n'),
  );
}

// ---------------------------------------------------------------------------
// Generate entrypoint.sh
// ---------------------------------------------------------------------------

function generateEntrypoint(services: ServiceDefinition[]): string {
  const templatePath = path.join(TEMPLATES_DIR, 'entrypoint.sh.template');

  let template: string;
  if (fs.existsSync(templatePath)) {
    template = fs.readFileSync(templatePath, 'utf-8');
  } else {
    template = `#!/bin/bash
set -e

echo "=== ClaudeOS v3 Starting ==="

# Load persisted env vars
if [ -f /data/.env ]; then
  echo "[entrypoint] Loading /data/.env"
  set -a
  source /data/.env
  set +a
fi

# Ensure data directories exist
mkdir -p /data/sessions /data/workspace

# Generate auth token if not set
if [ -z "$CLAUDE_OS_AUTH_TOKEN" ]; then
  export CLAUDE_OS_AUTH_TOKEN=$(openssl rand -hex 24)
  echo "CLAUDE_OS_AUTH_TOKEN=$CLAUDE_OS_AUTH_TOKEN" >> /data/.env
fi

echo "[entrypoint] Auth token: $CLAUDE_OS_AUTH_TOKEN"

# MODULE_INIT_PLACEHOLDER

# Start supervisor
echo "[entrypoint] Starting supervisord..."
exec /usr/bin/supervisord -c /etc/supervisord.conf
`;
  }

  // Generate module initialization blocks
  const initBlocks: string[] = [];
  for (const svc of services) {
    if (svc.healthCheck) {
      initBlocks.push(`
# Wait for ${svc.name} health check
echo "[entrypoint] Waiting for ${svc.name}..."
for i in $(seq 1 30); do
  if curl -s http://127.0.0.1:${svc.port || 80}${svc.healthCheck} > /dev/null 2>&1; then
    echo "[entrypoint] ${svc.name} is ready"
    break
  fi
  sleep 1
done
`);
    }
  }

  return template.replace(
    '# MODULE_INIT_PLACEHOLDER',
    initBlocks.join('\n'),
  );
}

// ---------------------------------------------------------------------------
// Build Manifest
// ---------------------------------------------------------------------------

function generateBuildManifest(
  modules: Array<{ manifest: ModuleManifest; modulePath: string }>,
  services: ServiceDefinition[],
): BuildManifest {
  return {
    version: '3.0.0',
    builtAt: new Date().toISOString(),
    modules: modules.map((m) => ({
      name: m.manifest.name,
      version: m.manifest.version,
      path: path.relative(ROOT_DIR, m.modulePath),
    })),
    services,
  };
}

// ---------------------------------------------------------------------------
// Main Build
// ---------------------------------------------------------------------------

async function build(): Promise<void> {
  console.log('[Build] ClaudeOS v3 Build Pipeline');
  console.log('[Build] ========================');

  // 1. Discover modules
  console.log('[Build] Discovering modules...');
  const discovered = discoverModules();
  console.log(`[Build] Found ${discovered.length} modules`);

  // 2. Load config
  const config = loadModulesConfig();

  // 3. Resolve dependencies
  console.log('[Build] Resolving dependencies...');
  const { modules, sorted } = buildStaticRegistry(discovered, config);
  console.log(`[Build] ${modules.length} modules enabled after dependency resolution`);

  // 4. Collect all services
  const allServices: ServiceDefinition[] = [];
  // Services would be collected from module manifests at runtime
  // For now, we generate empty placeholders

  // 5. Generate files
  ensureDir(GENERATED_DIR);

  console.log('[Build] Generating module-registry.ts...');
  const registryCode = generateModuleRegistry(modules);
  fs.writeFileSync(path.join(GENERATED_DIR, 'module-registry.ts'), registryCode);

  console.log('[Build] Generating api-routes.ts...');
  const apiRoutesCode = generateApiRoutes(modules);
  fs.writeFileSync(path.join(GENERATED_DIR, 'api-routes.ts'), apiRoutesCode);

  console.log('[Build] Generating supervisord.conf...');
  const supervisordConf = generateSupervisordConf(allServices);
  fs.writeFileSync(path.join(ROOT_DIR, 'supervisord.conf'), supervisordConf);

  console.log('[Build] Generating Dockerfile...');
  const dockerfile = generateDockerfile(allServices);
  fs.writeFileSync(path.join(ROOT_DIR, 'Dockerfile'), dockerfile);

  console.log('[Build] Generating entrypoint.sh...');
  const entrypoint = generateEntrypoint(allServices);
  fs.writeFileSync(path.join(ROOT_DIR, 'entrypoint.sh'), entrypoint);
  fs.chmodSync(path.join(ROOT_DIR, 'entrypoint.sh'), 0o755);

  console.log('[Build] Generating build-manifest.json...');
  const buildManifest = generateBuildManifest(modules, allServices);
  fs.writeFileSync(
    path.join(ROOT_DIR, 'build-manifest.json'),
    JSON.stringify(buildManifest, null, 2),
  );

  console.log('[Build] Build pipeline complete');
  console.log(`[Build] Modules: ${modules.map((m) => m.manifest.name).join(', ') || '(none)'}`);
}

// Run build
build().catch((err) => {
  console.error('[Build] FATAL:', err);
  process.exit(1);
});
